const cdpPort=Number(process.env.CDP_PORT??9246), appUrl=process.env.UI_URL??"http://127.0.0.1:4173/";
const v=await fetch(`http://127.0.0.1:${cdpPort}/json/version`).then(r=>r.json());
const ws=new WebSocket(v.webSocketDebuggerUrl);
await new Promise((res,rej)=>{ws.addEventListener("open",res,{once:true});ws.addEventListener("error",rej,{once:true});});
let id=0;const pending=new Map();
ws.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const w=pending.get(m.id);pending.delete(m.id);m.error?w.reject(new Error(m.error.message)):w.resolve(m.result);}});
const send=(method,params={},sessionId)=>{const rid=++id;return new Promise((resolve,reject)=>{pending.set(rid,{resolve,reject});ws.send(JSON.stringify({id:rid,method,params,...(sessionId?{sessionId}:{})}));});};
const {browserContextId}=await send("Target.createBrowserContext");
const {targetId}=await send("Target.createTarget",{url:appUrl,browserContextId});
const {sessionId}=await send("Target.attachToTarget",{targetId,flatten:true});
await send("Runtime.enable",{},sessionId);
const ev=async x=>{const r=await send("Runtime.evaluate",{expression:x,awaitPromise:true,returnByValue:true,userGesture:true},sessionId);if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description??r.exceptionDetails.text);return r.result?.value;};
const waitFor=async(x,ms=60000)=>{const t=Date.now();while(Date.now()-t<ms){if(await ev(`Boolean(${x})`))return true;await new Promise(r=>setTimeout(r,150));}return false;};
await waitFor("document.readyState==='complete' && document.querySelector('#view-overview')");
await ev(`document.querySelector('[data-view="evidence"]')?.click()||document.querySelector('[data-view="proof"]')?.click()`);
const TX="0x33642ef4a994dd63b5426a3835051f314cf422761d48000fcb1bcc4b4538efc5";
const setV=async(s,val)=>ev(`(()=>{const el=document.querySelector(${JSON.stringify(s)});if(!el)return 'MISSING';el.value=${JSON.stringify(val)};el.dispatchEvent(new Event('input',{bubbles:true}));return 'ok';})()`);
const out={};
out.proofUrlField=await ev(`document.querySelector('#proof-url')?.value ?? 'MISSING'`);
out.chainKeyField=await ev(`document.querySelector('#proof-chain-key')?.value ?? 'MISSING'`);
await setV("#proof-tx",TX);
await ev(`document.querySelector('#fetch-proof')?.click()`);
out.reachedTerminal=await waitFor(`document.querySelector('#proof-result')?.className.includes('success')||document.querySelector('#proof-result')?.className.includes('error')`,60000);
out.resultClass=await ev(`document.querySelector('#proof-result')?.className ?? ''`);
out.resultText=await ev(`document.querySelector('#proof-result')?.textContent ?? ''`);
out.exportEnabled=await ev(`document.querySelector('#export-proof') ? !document.querySelector('#export-proof').disabled : 'MISSING'`);
out.exportPayload=await ev(`(()=>{try{const p=currentProof;if(!p)return null;return{chainKey:p.chainKey,transactionHash:p.transactionHash,blockHeight:p.blockHeight,txBytesLen:p.encodedTransaction?.length,siblings:p.merkleProof?.siblings?.length,roots:p.continuityProof?.roots?.length,prover:p.prover};}catch(e){return 'ERR '+e.message;}})()`);
out.observedAt=new Date().toISOString();
console.log(JSON.stringify(out,null,2));
await send("Target.disposeBrowserContext",{browserContextId});ws.close();
