import { Contract, Interface, getAddress, isHexString, keccak256, type Provider, type TransactionReceipt, type TransactionResponse } from "ethers";
import { decodeAllocationEvent, decodeCheckpointEvent, hashAllocation, rebuildAllocations, serializeAllocation } from "./allocation.ts";
import { decodeNativeAllocation, decodeNativeCheckpoint } from "./receipt-evidence.ts";
import { PROGRAM_CLOSEOUT_VERSION, verifyCloseoutSafeCall, verifyProgramCloseout, type CloseoutAuthentication, type CloseoutReceipt, type CloseoutTargetAllocation, type ProgramCloseoutResult, type ProgramCloseoutV1, type TrustedCloseoutDeployment } from "./program-closeout.ts";
import { parseWorkAuthorizationPackage, type WorkAuthorizationPackageV1 } from "./work-authorization.ts";
import { AllocationKind, type Address, type AllocationV1, type Hex } from "./types.ts";
import { verifySafeRuntimeAtBlock, type SafeRuntimeSnapshotV1 } from "./safe-runtime.ts";

export interface CollectorDeployment extends TrustedCloseoutDeployment {
  sourceDeploymentBlock: number;
  targetDeploymentBlock: number;
}
export interface ProgramCloseoutLocator {
  epochId: Hex;
  authorizationPackets: WorkAuthorizationPackageV1[];
  source: { chainId: string; coordinator: Address; runtimeHash: Hex };
  target: { chainId: string; treasury: Address; runtimeHash: Hex; sourceChainKey: string };
}
export interface ProgramCollectorOptions {
  source: Provider;
  target: Provider;
  sourceAbi: readonly unknown[];
  targetAbi: readonly unknown[];
  deployment: CollectorDeployment;
  epochId: Hex;
  authorizationPackets?: readonly WorkAuthorizationPackageV1[];
  getNativeFrontier: (sourceChainKey: bigint, targetBlock: number) => Promise<{ exists: boolean; height: bigint; hash?: Hex }>;
}
export interface AllocationProvenanceV1 {
  allocationId: string; kind: number; amount: string; status: "paid" | "returned-credit" | "recognized-unpaid" | "unrecognized" | "error";
  legacyConsent: boolean;
  policyOutcome: { type: "milestone" | "return" | "unknown"; label: string; outcomeCode?: number; approval?: boolean; function?: string };
  source: { transactionHash?: Hex; blockNumber?: string; transactionIndex?: string; function?: string; executionKind?: "safe-call" | "direct"; safeCall?: ReturnType<typeof verifyCloseoutSafeCall>; safeRuntime?: SafeRuntimeSnapshotV1; errors: string[] };
  nativeAuthentication: { authenticationId?: Hex; blockHeight?: string; transactionIndex?: string; transactionHash?: Hex; storedAuthenticationTransactionHash?: Hex; classification?: "fresh-atomic" | "cached"; errors: string[] };
  recognition: { transactionHash?: Hex; economicId?: Hex; amount?: string; successful: boolean; errors: string[] };
  withdrawal: { transactionHash?: Hex; destination?: Address; successful: boolean; errors: string[] };
  errors: string[];
}
export interface CollectedProgramCloseoutV1 {
  version: "proofkey.work-treasury.collected-closeout.v1";
  status: ProgramCloseoutResult["status"];
  accountingStatus: ProgramCloseoutResult["status"];
  label: string;
  limitations: string[];
  errors: string[];
  epoch: { epochId: Hex; cap: string; available: string; unresolved: string; earned: string; returned: string; recognized: string; reserve: string; paid: string; outstanding: string; conservation: boolean; prefixComplete: boolean };
  allocations: AllocationProvenanceV1[];
  closeout: ProgramCloseoutV1;
  result: ProgramCloseoutResult;
  returnAccounting: string;
}
export function classifyNativeAuthentication(authenticationTransactionHash: Hex, recognitionTransactionHash: Hex, freshReverification?:{recognitionFunction:string;verified:boolean}): "fresh-atomic"|"cached" { const atomic=/^authenticateAndRecognize(?:Receipt|Checkpoint)$/.test(freshReverification?.recognitionFunction??"")&&freshReverification?.verified===true;return authenticationTransactionHash.toLowerCase()===recognitionTransactionHash.toLowerCase()||atomic?"fresh-atomic":"cached"; }
export function collectedEvidenceStatus(accounting:ProgramCloseoutResult["status"],rows:readonly AllocationProvenanceV1[],errors:readonly string[]):ProgramCloseoutResult["status"]{if(accounting==="invalid")return"invalid";const partial=errors.length>0||rows.some(row=>row.errors.length||row.source.errors.length||row.nativeAuthentication.errors.length||row.recognition.errors.length||row.withdrawal.errors.length);return accounting==="incomplete"||partial?"incomplete":"complete";}
export function validateNativeVerificationEvent(receipt:CloseoutReceipt,treasury:Address,sourceChainKey:string,blockHeight:string,transactionIndex:string):void{if(receipt.status!==1||receipt.to.toLowerCase()!==treasury.toLowerCase())throw new Error("native verification receipt is unsuccessful or targets another contract");const iface=new Interface(["event TransactionVerified(uint64 indexed chainKey,uint64 indexed height,uint64 transactionIndex)"]);const events=receipt.logs.filter(log=>log.address.toLowerCase()==="0x0000000000000000000000000000000000000fd2").map(log=>{try{return iface.parseLog({topics:log.topics,data:log.data});}catch{return null;}}).filter(event=>event?.name==="TransactionVerified"&&BigInt(event.args.chainKey)===BigInt(sourceChainKey)&&BigInt(event.args.height)===BigInt(blockHeight)&&BigInt(event.args.transactionIndex)===BigInt(transactionIndex));if(events.length!==1)throw new Error("native authentication receipt lacks exact verifier event");}
export function validateNativeAuthenticationEvidence(input:{receipt:CloseoutReceipt;treasury:Address;authenticationId:Hex;sourceChainKey:string;blockHeight:string;transactionIndex:string;encodedTransactionHash:Hex;nativeProfile:Hex}):void{
  if(input.receipt.status!==1||input.receipt.to.toLowerCase()!==input.treasury.toLowerCase())throw new Error("native authentication receipt is unsuccessful or targets another contract");
  const treasuryIface=new Interface(["event NativeTransactionAuthenticated(bytes32 indexed authenticationId,uint64 indexed blockHeight,uint64 transactionIndex,bytes32 encodedTransactionHash,bytes32 nativeProfile)"]);
  const auth=input.receipt.logs.filter(log=>log.address.toLowerCase()===input.treasury.toLowerCase()).map(log=>{try{return treasuryIface.parseLog({topics:log.topics,data:log.data});}catch{return null;}}).filter(event=>event?.name==="NativeTransactionAuthenticated"&&String(event.args.authenticationId).toLowerCase()===input.authenticationId.toLowerCase());
  if(auth.length!==1||BigInt(auth[0]!.args.blockHeight)!==BigInt(input.blockHeight)||BigInt(auth[0]!.args.transactionIndex)!==BigInt(input.transactionIndex)||String(auth[0]!.args.encodedTransactionHash).toLowerCase()!==input.encodedTransactionHash.toLowerCase()||String(auth[0]!.args.nativeProfile).toLowerCase()!==input.nativeProfile.toLowerCase())throw new Error("native authentication treasury event fields differ");
  validateNativeVerificationEvent(input.receipt,input.treasury,input.sourceChainKey,input.blockHeight,input.transactionIndex);
}
export function validateCollectedWithdrawal(receipt:CloseoutReceipt,treasury:Address,allocation:AllocationV1,paidDestination:Address):void{
  if(receipt.status!==1||receipt.to.toLowerCase()!==treasury.toLowerCase())throw new Error("withdrawal receipt is unsuccessful or targets another contract");const iface=new Interface(["function withdrawFor(bytes32,uint64)","function ownerWithdrawTo(bytes32,uint64,address)","event ClaimWithdrawn(bytes32 indexed epochId,uint64 indexed allocationId,uint8 kind,address indexed claimOwner,address destination,uint256 amount)"]);const tx=iface.parseTransaction({data:receipt.input});if(!tx||!['withdrawFor','ownerWithdrawTo'].includes(tx.name)||String(tx.args[0]).toLowerCase()!==allocation.epochId.toLowerCase()||BigInt(tx.args[1])!==allocation.allocationId)throw new Error("withdrawal calldata identifies another claim");if(tx.name==="withdrawFor"&&paidDestination.toLowerCase()!==allocation.destination.toLowerCase())throw new Error("fixed withdrawal destination differs");if(tx.name==="ownerWithdrawTo"&&(String(tx.args[2]).toLowerCase()!==paidDestination.toLowerCase()||receipt.from.toLowerCase()!==allocation.claimOwner.toLowerCase()))throw new Error("owner redirect evidence differs");const events=receipt.logs.filter(log=>log.address.toLowerCase()===treasury.toLowerCase()).map(log=>{try{return iface.parseLog({topics:log.topics,data:log.data});}catch{return null;}}).filter(event=>event?.name==="ClaimWithdrawn"&&String(event.args.epochId).toLowerCase()===allocation.epochId.toLowerCase()&&BigInt(event.args.allocationId)===allocation.allocationId&&BigInt(event.args.amount)===allocation.amount&&String(event.args.destination).toLowerCase()===paidDestination.toLowerCase());if(events.length!==1)throw new Error("withdrawal receipt lacks exact ClaimWithdrawn event");
}
export function validateAuthenticatedCheckpointReceipt(receipt:CloseoutReceipt,ordinal:number,coordinator:Address,expected:{epochId:Hex;root:Hex;leafCount:number}):void{if(receipt.status!==1)throw new Error("authenticated source receipt is unsuccessful");const log=receipt.logs[ordinal];if(!log||log.address.toLowerCase()!==coordinator.toLowerCase())throw new Error("authenticated checkpoint log is unavailable at the pinned coordinator");const checkpoint=decodeCheckpointEvent(log.topics,log.data);if(checkpoint.epochId.toLowerCase()!==expected.epochId.toLowerCase()||checkpoint.root.toLowerCase()!==expected.root.toLowerCase()||checkpoint.leafCount!==expected.leafCount)throw new Error("authenticated source checkpoint identity differs");}
export function assertStableFinalizedSnapshots(initial:{source:{number:number;hash:Hex};target:{number:number;hash:Hex}},reread:{source:{number:number;hash:Hex}|null;target:{number:number;hash:Hex}|null;sourceFinalized:number;targetFinalized:number}):void{if(!reread.source||!reread.target||reread.source.hash.toLowerCase()!==initial.source.hash.toLowerCase()||reread.target.hash.toLowerCase()!==initial.target.hash.toLowerCase()||reread.sourceFinalized<initial.source.number||reread.targetFinalized<initial.target.number)throw new Error("pinned finalized snapshots changed during collection");}

function ownRecord(value: unknown, label: string): Record<string, any> { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} must be an object`); return value as Record<string, any>; }
function only(value: Record<string, any>, allowed: readonly string[], label: string) { for (const key of Object.keys(value)) if (!allowed.includes(key)) throw new Error(`${label} contains unsupported field ${key}`); }
function address(value: unknown, label: string): Address { try { return getAddress(String(value)) as Address; } catch { throw new Error(`${label} is not an address`); } }
function hex32(value: unknown, label: string): Hex { if (typeof value !== "string" || !isHexString(value, 32)) throw new Error(`${label} must be bytes32`); return value as Hex; }
function decimal(value: unknown, label: string): string { const text = String(value); if (!/^(0|[1-9][0-9]*)$/.test(text)) throw new Error(`${label} must be canonical decimal text`); return text; }

/** Reduces an exported report to locators. Result/provenance fields are deliberately ignored as evidence. */
export function parseProgramCloseoutLocator(input: unknown): ProgramCloseoutLocator {
  const root = ownRecord(typeof input === "string" ? JSON.parse(input) : input, "closeout export");
  const raw = root.version === PROGRAM_CLOSEOUT_VERSION;
  only(root, raw ? ["version","source","target","epochs"] : ["version", "status", "accountingStatus", "label", "limitations", "errors", "epoch", "allocations", "closeout", "result", "returnAccounting"], "closeout export");
  const closeout = ownRecord(raw ? root : root.closeout, "closeout");
  if (closeout.version !== PROGRAM_CLOSEOUT_VERSION) throw new Error("unsupported closeout locator version");
  const source = ownRecord(closeout.source, "closeout.source"), target = ownRecord(closeout.target, "closeout.target");
  if (!Array.isArray(closeout.epochs) || closeout.epochs.length !== 1) throw new Error("closeout locator requires exactly one epoch");
  const epoch = ownRecord(closeout.epochs[0], "closeout epoch");
  const packets = Array.isArray(epoch.authorizations) ? epoch.authorizations.map((record: any) => parseWorkAuthorizationPackage(ownRecord(record, "authorization record").packet)) : [];
  if(new Set(packets.map(packet=>packet.orderId.toLowerCase())).size!==packets.length)throw new Error("duplicate authorization packet locator");
  return {
    epochId: hex32(epoch.epochId, "epochId"), authorizationPackets: packets,
    source: { chainId: decimal(source.snapshot?.chainId, "source chainId"), coordinator: address(source.coordinator, "source coordinator"), runtimeHash: hex32(source.runtimeHash, "source runtimeHash") },
    target: { chainId: decimal(target.snapshot?.chainId, "target chainId"), treasury: address(target.treasury, "target treasury"), runtimeHash: hex32(target.runtimeHash, "target runtimeHash"), sourceChainKey: decimal(target.sourceChainKey, "source chain key") },
  };
}

function serializedAllocation(raw: any) {
  const value = raw?.epochId ? raw : raw?.[0]; const field = (name: string, index: number) => value?.[name] ?? value?.[index];
  return serializeAllocation({ epochId: field("epochId",0), allocationId: BigInt(field("allocationId",1)), treeIndex: Number(field("treeIndex",2)), kind: Number(field("kind",3)), orderId: field("orderId",4), milestoneId: Number(field("milestoneId",5)), role: Number(field("role",6)), asset: field("asset",7), amount: BigInt(field("amount",8)), claimOwner: field("claimOwner",9), destination: field("destination",10), policyHash: field("policyHash",11), evidenceHash: field("evidenceHash",12) });
}
async function receiptEvidence(provider: Provider, receipt: TransactionReceipt): Promise<CloseoutReceipt> {
  const tx = await provider.getTransaction(receipt.hash); if (!tx?.to || !receipt.blockHash) throw new Error(`missing transaction data for ${receipt.hash}`);
  return { transactionHash: receipt.hash as Hex, blockNumber: String(receipt.blockNumber), blockHash: receipt.blockHash as Hex, status: receipt.status ?? 0, to: getAddress(tx.to) as Address, from: getAddress(tx.from) as Address, input: tx.data as Hex, logs: receipt.logs.map(log => ({ address: getAddress(log.address) as Address, topics: [...log.topics] as Hex[], data: log.data as Hex })) };
}
function allocationFromEvent(event: any): AllocationV1 { return decodeAllocationEvent(event.topics, event.data); }
function outcomeLabel(code: number): string { return ({1:"declined",2:"pending-expired",3:"no-delivery",4:"approved",5:"monitoring-default",6:"committee-ruling",7:"committee-timeout",8:"mutual-settlement"} as Record<number,string>)[code] ?? `unknown-${code}`; }
function policyOutcome(iface: Interface, receipt: TransactionReceipt, coordinator: Address, allocation: AllocationV1, innerData?: Hex): AllocationProvenanceV1["policyOutcome"] {
  for (const log of receipt.logs) {
    if (log.address.toLowerCase() !== coordinator.toLowerCase()) continue;
    try { const event = iface.parseLog(log); if (event?.name === "MilestoneFinalized" && String(event.args.orderId).toLowerCase() === allocation.orderId.toLowerCase() && Number(event.args.milestoneId) === allocation.milestoneId) { const code = Number(event.args.outcome); return { type:"milestone", label:outcomeLabel(code), outcomeCode:code, approval:code===4 }; } } catch {}
  }
  let name: string | undefined; try { name = iface.parseTransaction({ data: innerData ?? "0x" })?.name; } catch {}
  if (allocation.kind === AllocationKind.RETURN) return { type:"return", label:name === "releaseFree" ? "authorized-free-return" : name === "sweepAvailable" ? "draining-sweep-return" : name === "expireUninitializedEpoch" ? "uninitialized-expiry-return" : "return-allocation", ...(name ? { function:name } : {}) };
  return { type:"unknown", label:"terminal-event-not-classified", ...(name ? { function:name } : {}) };
}

/** Fresh, read-only collection at compatible finalized source and target snapshots. */
export async function collectProgramCloseout(options: ProgramCollectorOptions): Promise<CollectedProgramCloseoutV1> {
  const { source, target, deployment: d } = options;
  const rawChainId = async(provider:Provider) => typeof (provider as any).send === "function" ? BigInt(await (provider as any).send("eth_chainId",[])).toString() : (await provider.getNetwork()).chainId.toString();
  const [sourceChain, targetChain, sourceFinal, targetFinal] = await Promise.all([rawChainId(source), rawChainId(target), source.getBlock("finalized"), target.getBlock("finalized")]);
  if (sourceChain !== d.sourceChainId || targetChain !== d.targetChainId) throw new Error("RPC chain IDs differ from trusted deployment");
  if (!sourceFinal?.hash || !targetFinal?.hash) throw new Error("both RPCs must expose finalized blocks");
  const [sourceCode,targetCode] = await Promise.all([source.getCode(d.sourceCoordinator,sourceFinal.number),target.getCode(d.targetTreasury,targetFinal.number)]);
  if (keccak256(sourceCode).toLowerCase() !== d.sourceRuntimeHash.toLowerCase() || keccak256(targetCode).toLowerCase() !== d.targetRuntimeHash.toLowerCase()) throw new Error("live runtime differs from trusted deployment");
  const coordinator = new Contract(d.sourceCoordinator, options.sourceAbi as any, source), treasury = new Contract(d.targetTreasury, options.targetAbi as any, target);
  const sourceIface = new Interface(options.sourceAbi as any), targetIface = new Interface(options.targetAbi as any);
  const rawState = await coordinator.epochState.staticCall(options.epochId,{blockTag:sourceFinal.number});
  const leafCount = Number(rawState.leafCount ?? rawState[2]);
  const allocations = await Promise.all(Array.from({length:leafCount},(_,index)=>coordinator.allocationAt.staticCall(options.epochId,index,{blockTag:sourceFinal.number}).then((raw:any)=>serializedAllocation(raw))));
  const normalized = allocations.map(item => ({...item,allocationId:BigInt(item.allocationId),amount:BigInt(item.amount)} as AllocationV1));
  const rebuilt = rebuildAllocations(normalized);
  const root = (rawState.root ?? rawState[3]) as Hex;
  if (rebuilt.root.toLowerCase() !== root.toLowerCase()) throw new Error("source allocation root reconstruction failed");
  const storedLeaves=await Promise.all(normalized.map((_,index)=>coordinator.leafHashAt.staticCall(options.epochId,index,{blockTag:sourceFinal.number})));
  if(storedLeaves.some((leaf:string,index:number)=>leaf.toLowerCase()!==hashAllocation(normalized[index]!).toLowerCase()))throw new Error("source allocation leaf getter differs from canonical leaf");
  const [config,account,nativeProfile] = await Promise.all([treasury.epochConfig.staticCall(options.epochId,{blockTag:targetFinal.number}),treasury.epochAccount.staticCall(options.epochId,{blockTag:targetFinal.number}),treasury.nativeProfile.staticCall({blockTag:targetFinal.number})]);
  if (BigInt(config.sourceChainId) !== BigInt(d.sourceChainId) || BigInt(config.sourceChainKey) !== BigInt(d.sourceChainKey) || String(config.sourceCoordinator).toLowerCase() !== d.sourceCoordinator.toLowerCase() || BigInt(config.targetChainId) !== BigInt(d.targetChainId) || String(config.targetTreasury).toLowerCase() !== d.targetTreasury.toLowerCase()) throw new Error("funded epoch domain differs from trusted deployment");
  const [recognizedLogs,withdrawnLogs,sourceAllocationLogs,frontier] = await Promise.all([
    treasury.queryFilter(treasury.filters.AllocationRecognized(options.epochId),d.targetDeploymentBlock,targetFinal.number), treasury.queryFilter(treasury.filters.ClaimWithdrawn(options.epochId),d.targetDeploymentBlock,targetFinal.number),
    coordinator.queryFilter(coordinator.filters.AllocationCreated(options.epochId),d.sourceDeploymentBlock,sourceFinal.number), options.getNativeFrontier(BigInt(d.sourceChainKey),targetFinal.number),
  ]);
  if (!frontier.exists) throw new Error("target native frontier is unavailable");
  const recognizedById = new Map(recognizedLogs.map((log:any)=>[String(log.args.allocationId),log])), withdrawnById = new Map(withdrawnLogs.map((log:any)=>[String(log.args.allocationId),log])), sourceById = new Map(sourceAllocationLogs.map((log:any)=>[String(log.args.allocationId),log]));
  const verifier = new Contract(await treasury.VERIFIER.staticCall({blockTag:targetFinal.number}),["function calculateTxIndex((bytes32 root,(bytes32 hash,bool isLeft)[] siblings)) pure returns(uint64)"],target);
  const targetAllocations: CloseoutTargetAllocation[] = [], provenance: AllocationProvenanceV1[] = [];
  for (const allocation of normalized) {
    const id = String(allocation.allocationId), row: AllocationProvenanceV1 = { allocationId:id,kind:allocation.kind,amount:String(allocation.amount),status:"unrecognized",legacyConsent:true,policyOutcome:{type:"unknown",label:"not-collected"},source:{errors:[]},nativeAuthentication:{errors:[]},recognition:{successful:false,errors:[]},withdrawal:{successful:false,errors:[]},errors:[] };
    const targetItem: CloseoutTargetAllocation = {allocation:serializeAllocation(allocation),recognized:false};
    try {
      const sourceEvent:any = sourceById.get(id); if (!sourceEvent || hashAllocation(allocationFromEvent(sourceEvent)).toLowerCase() !== hashAllocation(allocation).toLowerCase()) throw new Error("exact source AllocationCreated event is missing");
      const [sourceReceipt,sourceTx] = await Promise.all([source.getTransactionReceipt(sourceEvent.transactionHash),source.getTransaction(sourceEvent.transactionHash)]); if (!sourceReceipt || !sourceTx?.to || sourceReceipt.status!==1) throw new Error("source terminal transaction is missing or unsuccessful");
      row.source.transactionHash=sourceTx.hash as Hex; row.source.blockNumber=String(sourceReceipt.blockNumber); row.source.transactionIndex=String(sourceReceipt.index);
      let innerData=sourceTx.data as Hex; row.source.executionKind="direct";
      if (sourceTx.to.toLowerCase()===String(config.sourceSafe).toLowerCase()) {
        const success = sourceReceipt.logs.map(log=>{try{return new Interface(["event ExecutionSuccess(bytes32 indexed txHash,uint256 payment)"]).parseLog(log);}catch{return null;}}).find(event=>event?.name==="ExecutionSuccess"); if(!success)throw new Error("Safe terminal source transaction lacks ExecutionSuccess");
        const nonce=await new Contract(config.sourceSafe,["function nonce() view returns(uint256)"],source).nonce.staticCall({blockTag:Math.max(0,sourceReceipt.blockNumber-1)});
        const safe=verifyCloseoutSafeCall({transaction:{to:sourceTx.to,data:sourceTx.data},receipt:{status:sourceReceipt.status,logs:(await receiptEvidence(source,sourceReceipt)).logs},safe:config.sourceSafe,coordinator:d.sourceCoordinator,chainId:d.sourceChainId,nonce:String(nonce),expectedSafeTxHash:success.args.txHash}); row.source.safeCall=safe;row.source.safeRuntime=await verifySafeRuntimeAtBlock({provider:source,safe:config.sourceSafe,blockNumber:sourceReceipt.blockNumber,blockHash:sourceReceipt.blockHash as Hex,chainId:d.sourceChainId});row.source.executionKind="safe-call"; innerData=safe.innerData;
      }
      row.source.function=sourceIface.parseTransaction({data:innerData})?.name; row.policyOutcome=policyOutcome(sourceIface,sourceReceipt,d.sourceCoordinator,allocation,innerData);
    } catch(error){row.source.errors.push((error as Error).message);row.errors.push((error as Error).message);}
    const recognition:any=recognizedById.get(id);
    if (recognition) try {
      const [receipt,tx,readback]=await Promise.all([target.getTransactionReceipt(recognition.transactionHash),target.getTransaction(recognition.transactionHash),treasury.recognizedAllocation.staticCall(options.epochId,allocation.allocationId,{blockTag:targetFinal.number})]); if(!receipt||!tx||receipt.status!==1)throw new Error("recognition transaction is missing or unsuccessful");
      targetItem.recognized=true;targetItem.recognizedAllocation=serializedAllocation(readback);targetItem.recognitionReceipt=await receiptEvidence(target,receipt);
      const parsed=targetIface.parseTransaction({data:tx.data});if(!parsed)throw new Error("recognition calldata is unsupported");let authId:Hex,checkpointEvidence:CloseoutAuthentication["checkpoint"]|undefined;
      if(parsed.name==="recognizeFromCheckpoint"||parsed.name==="authenticateAndRecognizeCheckpoint"){
        let checkpointId:Hex;if(parsed.name==="recognizeFromCheckpoint")checkpointId=parsed.args[0];else{const event=receipt.logs.map(log=>{try{return targetIface.parseLog(log);}catch{return null;}}).find(event=>event?.name==="CheckpointImported");if(!event)throw new Error("atomic checkpoint import event missing");checkpointId=event.args.checkpointId;}
        const c=await treasury.checkpoint.staticCall(checkpointId,{blockTag:targetFinal.number});authId=c.authenticationId;checkpointEvidence={checkpointId,epochId:c.checkpoint.epochId,root:c.checkpoint.root,leafCount:Number(c.checkpoint.leafCount),authenticationId:c.authenticationId,logOrdinal:Number(c.logOrdinal),blockHeight:String(c.position.blockHeight),transactionIndex:String(c.position.transactionIndex),exists:Boolean(c.exists)};
      }else{let position:any,bytes:Hex,ordinal:number;if(parsed.name==="recognizeFromReceipt"){position={blockHeight:BigInt(parsed.args[0].blockHeight),transactionIndex:BigInt(parsed.args[0].transactionIndex)};bytes=parsed.args[1];ordinal=Number(parsed.args[2]);}else if(parsed.name==="authenticateAndRecognizeReceipt"){const proof=parsed.args[0],merkle={root:proof.merkleProof.root,siblings:Array.from(proof.merkleProof.siblings,(x:any)=>({hash:x.hash,isLeft:x.isLeft}))};position={blockHeight:BigInt(proof.blockHeight),transactionIndex:await verifier.calculateTxIndex.staticCall(merkle,{blockTag:targetFinal.number})};bytes=proof.encodedTransaction;ordinal=Number(parsed.args[1]);}else throw new Error(`unsupported recognition function ${parsed.name}`);if(hashAllocation(decodeNativeAllocation(bytes,ordinal,d.sourceCoordinator)).toLowerCase()!==hashAllocation(allocation).toLowerCase())throw new Error("native receipt selected another allocation");authId=await treasury.authenticationId.staticCall(position,keccak256(bytes),{blockTag:targetFinal.number});}
      const auth=await treasury.authentication.staticCall(authId,{blockTag:targetFinal.number});if(!auth.exists||String(nativeProfile).length!==66)throw new Error("native authentication readback is missing");targetItem.authentication={authenticationId:authId,blockHeight:String(auth.blockHeight),transactionIndex:String(auth.transactionIndex),encodedTransactionHash:auth.encodedTransactionHash,exists:true,...(checkpointEvidence?{checkpoint:checkpointEvidence}:{})};
      const authenticatedBlock=await source.getBlock(Number(auth.blockHeight),true);const authenticatedSourceTx=authenticatedBlock?.getPrefetchedTransaction(Number(auth.transactionIndex));const authenticatedSourceReceipt=authenticatedSourceTx?await source.getTransactionReceipt(authenticatedSourceTx.hash):null;if(!authenticatedSourceTx||!authenticatedSourceReceipt||authenticatedSourceReceipt.status!==1||authenticatedSourceReceipt.index!==Number(auth.transactionIndex))throw new Error("authenticated source transaction position is unavailable");
      if(checkpointEvidence)validateAuthenticatedCheckpointReceipt(await receiptEvidence(source,authenticatedSourceReceipt),checkpointEvidence.logOrdinal,d.sourceCoordinator,{epochId:options.epochId,root:checkpointEvidence.root,leafCount:checkpointEvidence.leafCount});else if(row.source.transactionHash&&authenticatedSourceTx.hash.toLowerCase()!==row.source.transactionHash.toLowerCase())throw new Error("receipt authentication source transaction differs from allocation terminal transaction");
      const authEvents=await treasury.queryFilter(treasury.filters.NativeTransactionAuthenticated(authId),d.targetDeploymentBlock,targetFinal.number);if(authEvents.length!==1)throw new Error("native authentication must have one recorded treasury event");const authEvent:any=authEvents[0],authReceipt=await target.getTransactionReceipt(authEvent.transactionHash);if(!authReceipt)throw new Error("native authentication transaction receipt is unavailable");validateNativeAuthenticationEvidence({receipt:await receiptEvidence(target,authReceipt),treasury:d.targetTreasury,authenticationId:authId,sourceChainKey:d.sourceChainKey,blockHeight:String(auth.blockHeight),transactionIndex:String(auth.transactionIndex),encodedTransactionHash:auth.encodedTransactionHash,nativeProfile});let recognitionReverified=false;if(/^authenticateAndRecognize(?:Receipt|Checkpoint)$/.test(parsed.name)){validateNativeVerificationEvent(targetItem.recognitionReceipt,d.targetTreasury,d.sourceChainKey,String(auth.blockHeight),String(auth.transactionIndex));recognitionReverified=true;}const classification=classifyNativeAuthentication(authEvent.transactionHash,tx.hash as Hex,{recognitionFunction:parsed.name,verified:recognitionReverified});row.nativeAuthentication={authenticationId:authId,blockHeight:String(auth.blockHeight),transactionIndex:String(auth.transactionIndex),transactionHash:(classification==="fresh-atomic"?tx.hash:authEvent.transactionHash) as Hex,storedAuthenticationTransactionHash:authEvent.transactionHash,classification,errors:[]};
      row.recognition={transactionHash:tx.hash as Hex,economicId:recognition.args.economicId,amount:String(recognition.args.amount),successful:true,errors:[]};row.status=allocation.kind===AllocationKind.RETURN?"returned-credit":"recognized-unpaid";
    }catch(error){row.recognition.errors.push((error as Error).message);row.nativeAuthentication.errors.push((error as Error).message);row.errors.push((error as Error).message);}
    if(allocation.kind===AllocationKind.WORK||allocation.kind===AllocationKind.FEE){const completed=await treasury.completedClaim.staticCall(options.epochId,allocation.allocationId,{blockTag:targetFinal.number});targetItem.completedClaim={allocation:serializedAllocation(completed.allocation??completed[0]),withdrawn:Boolean(completed.withdrawn??completed[1]),paidDestination:completed.paidDestination??completed[2]};const withdrawal:any=withdrawnById.get(id);if(withdrawal){const wr=await target.getTransactionReceipt(withdrawal.transactionHash);if(wr){targetItem.withdrawalReceipt=await receiptEvidence(target,wr);try{validateCollectedWithdrawal(targetItem.withdrawalReceipt,d.targetTreasury,allocation,targetItem.completedClaim.paidDestination);row.withdrawal={transactionHash:withdrawal.transactionHash,destination:withdrawal.args.destination,successful:true,errors:[]};row.status="paid";}catch(error){row.withdrawal.errors.push((error as Error).message);row.errors.push((error as Error).message);}}}if(completed.withdrawn&&!withdrawal){row.withdrawal.errors.push("completed claim has no collected ClaimWithdrawn event");row.errors.push("withdrawal provenance missing");}}
    targetAllocations.push(targetItem);provenance.push(row);
  }
  const packets=(options.authorizationPackets??[]).map(parseWorkAuthorizationPackage);if(new Set(packets.map(packet=>packet.orderId.toLowerCase())).size!==packets.length)throw new Error("duplicate authorization packet locator");const authorizations:NonNullable<ProgramCloseoutV1["epochs"][number]["authorizations"]>=[],collectorErrors:string[]=[];const safeEventIface=new Interface(["event ExecutionSuccess(bytes32 indexed txHash,uint256 payment)"]);
  for(const packet of packets)try{if(packet.authorization.targetFunding.epochId.toLowerCase()!==options.epochId.toLowerCase())throw new Error(`authorization ${packet.orderId} belongs to another epoch`);const events=await coordinator.queryFilter(coordinator.filters.OrderReserved(options.epochId,packet.orderId),d.sourceDeploymentBlock,sourceFinal.number);const accepted:any=events.find((event:any)=>event.args.agreed===true);if(!accepted)throw new Error(`authorization ${packet.orderId} has no finalized agreed event`);const [receipt,tx,order]=await Promise.all([source.getTransactionReceipt(accepted.transactionHash),source.getTransaction(accepted.transactionHash),coordinator.order.staticCall(packet.orderId,{blockTag:sourceFinal.number})]);if(!receipt||!tx?.to)throw new Error("authorization acceptance receipt unavailable");const success=receipt.logs.map(log=>{try{return safeEventIface.parseLog(log);}catch{return null;}}).find(event=>event?.name==="ExecutionSuccess");if(!success)throw new Error("authorization acceptance lacks Safe success");const nonce=await new Contract(packet.authorization.epochConfig.sourceSafe,["function nonce() view returns(uint256)"],source).nonce.staticCall({blockTag:Math.max(0,receipt.blockNumber-1)});await verifySafeRuntimeAtBlock({provider:source,safe:packet.authorization.epochConfig.sourceSafe,blockNumber:receipt.blockNumber,blockHash:receipt.blockHash as Hex,chainId:d.sourceChainId});authorizations.push({packet,acceptanceReceipt:await receiptEvidence(source,receipt),safeExecution:{nonce:String(nonce),expectedSafeTxHash:success.args.txHash},sourceOrder:{exists:Boolean(order.exists),agreed:Boolean(order.agreed),epochId:order.epochId,termsHash:order.termsHash,worker:order.worker}});}catch(error){collectorErrors.push(`authorization ${packet.orderId}: ${(error as Error).message}`);}
  const closeout:ProgramCloseoutV1={version:PROGRAM_CLOSEOUT_VERSION,source:{coordinator:d.sourceCoordinator,runtimeHash:d.sourceRuntimeHash,snapshot:{chainId:d.sourceChainId,blockNumber:String(sourceFinal.number),blockHash:sourceFinal.hash as Hex,finality:"rpc-finalized"}},target:{treasury:d.targetTreasury,runtimeHash:d.targetRuntimeHash,snapshot:{chainId:d.targetChainId,blockNumber:String(targetFinal.number),blockHash:targetFinal.hash as Hex,finality:"rpc-finalized"},sourceChainKey:d.sourceChainKey,nativeAttestedSourceHeight:String(frontier.height)},epochs:[{epochId:options.epochId,cap:String(config.cap),source:{available:String(rawState.available),unresolved:String(rawState.unresolved),earned:String(rawState.earned),returned:String(rawState.returned),phase:Number(rawState.phase),leafCount,root,allocations},target:{reserve:String(account.reserve),recognized:String(account.recognized),funded:Boolean(account.funded),allocations:targetAllocations,refundOwnerFreeBalance:String(await treasury.freeBalance.staticCall(config.refundBeneficiary,{blockTag:targetFinal.number}))},...(authorizations.length?{authorizations}:{})}]};
  const [sourceAgain,targetAgain,sourceFinalAgain,targetFinalAgain]=await Promise.all([source.getBlock(sourceFinal.number),target.getBlock(targetFinal.number),source.getBlock("finalized"),target.getBlock("finalized")]);assertStableFinalizedSnapshots({source:{number:sourceFinal.number,hash:sourceFinal.hash as Hex},target:{number:targetFinal.number,hash:targetFinal.hash as Hex}},{source:sourceAgain?.hash?{number:sourceAgain.number,hash:sourceAgain.hash as Hex}:null,target:targetAgain?.hash?{number:targetAgain.number,hash:targetAgain.hash as Hex}:null,sourceFinalized:sourceFinalAgain?.number??-1,targetFinalized:targetFinalAgain?.number??-1});
  const result=verifyProgramCloseout(closeout,d);for(const row of provenance)row.legacyConsent=result.consent.legacyOrders.some(order=>order.toLowerCase()===normalized.find(a=>String(a.allocationId)===row.allocationId)?.orderId.toLowerCase());const status=collectedEvidenceStatus(result.status,provenance,collectorErrors);
  const epoch=result.totals;return{version:"proofkey.work-treasury.collected-closeout.v1",status,accountingStatus:result.status,label:status==="complete"?"Complete program closeout":status==="incomplete"&&result.status==="complete"?"Accounting complete; provenance evidence partial":status==="incomplete"?"Program closeout is incomplete":"Program closeout evidence is invalid",limitations:["This proves recorded treasury transfers, not work quality, recipient independence, adoption, or later beneficial control.","Safe CALL provenance includes a historical canonical Safe 1.4.1 proxy and singleton runtime check; it does not prove current owners or participant independence.","Totals cover this selected epoch and are not global treasury in/out accounting."],errors:collectorErrors,epoch:{epochId:options.epochId,cap:String(epoch.cap),available:String(rawState.available),unresolved:String(rawState.unresolved),earned:String(epoch.earned),returned:String(epoch.returned),recognized:String(account.recognized),reserve:String(account.reserve),paid:String(epoch.paid),outstanding:String(epoch.outstanding),conservation:BigInt(config.cap)===BigInt(rawState.available)+BigInt(rawState.unresolved)+BigInt(rawState.earned)+BigInt(rawState.returned),prefixComplete:allocations.length===leafCount&&rebuilt.root.toLowerCase()===root.toLowerCase()},allocations:provenance,closeout,result,returnAccounting:"RETURN recognition is epoch-specific; any later withdrawal comes from the refund owner's fungible freeBalance and cannot be attributed to one epoch."};
}

export function stringifyCollectedProgramCloseout(value: CollectedProgramCloseoutV1): string { return JSON.stringify(value,(_key,item)=>typeof item==="bigint"?item.toString():item,2); }
